# Generated by Django 4.1.3 on 2022-12-07 08:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Mon'), ('Tues', 'Tues'), ('Wens', 'Wens')], max_length=100, null=True),
        ),
    ]
