# Generated by Django 4.1.3 on 2022-12-07 09:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_movie_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="tag",
        ),
        migrations.AddField(
            model_name="movie",
            name="sent_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("Mon", "Mon"), ("Tues", "Tues"), ("Wens", "Wens")],
                max_length=100,
                null=True,
            ),
        ),
    ]
