# Generated by Django 4.1.3 on 2022-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_tag_alter_movie_sent_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
    ]
