# Generated by Django 4.1.3 on 2022-12-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_movie_recommended"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="sent_days",
            new_name="tags",
        ),
    ]
