# Generated by Django 4.1.3 on 2022-12-08 05:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_sent_days_movie_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("2D", "2D"), ("3D", "3D")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.ManyToManyField(to="core.language"),
        ),
    ]
