# Generated by Django 4.1.3 on 2022-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_language_movie_type_movie_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(default=1),
            preserve_default=False,
        ),
    ]
