# Generated by Django 4.1.3 on 2022-12-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_movie_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="duration",
        ),
    ]
