# Generated by Django 4.1.3 on 2022-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_movie_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
