# Generated by Django 4.1.3 on 2022-12-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_movie_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
